// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/thinhcompany/ecommerce-ver-2/internal/handler"
	"github.com/thinhcompany/ecommerce-ver-2/internal/repo"
	"github.com/thinhcompany/ecommerce-ver-2/internal/service"
)

// Injectors from wire.go:

func InitUserHandler() *handler.UserHandler {
	iUserRepo := repo.NewUserRepo()
	iUserService := service.NewUserService(iUserRepo)
	userHandler := handler.NewUserHandler(iUserService)
	return userHandler
}
