server:
  port: 8081
  mode: "dev"  # "dev", "prod"

smtp:
  host: "smtp.gmail.com"
  port: 587
  username: "thinhproee@gmail.com"
  password: "rmakdncnfplgdrfr"


mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "1234"
  dbname: "go_eco"
  maxIdleConns: 10
  maxOpenConns: 100
  connexMaxLifetime: 3600

redis:
  addr: "localhost:6379"
  password: ""        # leave empty if no auth
  db: 0
  poolsize: 10


jwt:
  secret: supersecretkey

log:
  logLevel: "debug"
  fileLogName: "./storages/logs/dev.001.log"
  maxSize: 10         # in megabytes
  maxBackups: 5
  maxAge: 28          # days
  compress: true