server:
  port: 8080
  mode: "dev"

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "1234"
  dbname: "go_eco"
  maxIdleConns: 10
  maxOpenConns: 100
  connexMaxLifetime: 3600

jwt:
  secret: supersecretkey

log:
  logLevel: "debug"
  fileLogName: "./storages/logs/dev.001.log"
  maxSize: 10         # in megabytes
  maxBackups: 5
  maxAge: 28          # days
  compress: true

redis:
  addr: "localhost:6379"
  password: ""        # leave empty if no auth
  db: 0
  poolsize: 10

