// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

// User Account Table
type PreGoCrmUserC struct {
	// Account ID
	UsrID uint32
	// Email
	UsrEmail string
	// Phone Number
	UsrPhone string
	// Username
	UsrUsername string
	// Password (hashed)
	UsrPassword string
	// Creation Timestamp
	UsrCreatedAt int32
	// Update Timestamp
	UsrUpdatedAt int32
	// Creation IP
	UsrCreateIpAt string
	// Last Login Timestamp
	UsrLastLoginAt int32
	// Last Login IP
	UsrLastLoginIpAt string
	// Login Times
	UsrLoginTimes int32
	// Status: 1=enabled, 0=disabled, -1=deleted
	UsrStatus bool
}
